### ISSUE TITLE
6s

### ISSUE THREAD

**Issue by ymsheng** [gitKun/DRCornerViewExtension#1]

**Comment by ymsheng** [comment]
我调用此方法做了imageview的圆角后，imageview周边会有0.5像素的线。应该是在画内部的遮盖时，没有把边上盖住

**Comment by gitKun** [comment]
@ymsheng 我这边测了一下设置成圆形的图片和边角为圆弧的情形,但是都没出现你说的情况,能提供个demo地址吗?

**Comment by gitKun** [comment]
请使用真机和最新的示例代码进行测试，如果还有问题欢迎提出
