### ISSUE TITLE
请问下这种问题是什么原因造成的呢?

### ISSUE THREAD

**Issue by xingze0308** [gitKun/DRCornerViewExtension#3]
![c692c765-5065-4975-841b-48612ce21618](https://user-images.githubusercontent.com/16461294/28002442-c8509b5e-6567-11e7-8a17-185ed69894a5.png)

**Comment by xingze0308** [comment]
@gitKun 上面的Label 是我把多余的空格删除掉 给了label一个固定宽度就没问题 而下面的label是你demo 中的

**Comment by gitKun** [comment]
@xingze0308  这是因为 xib文件中这个label 的宽度没有给约束，你把空格去掉后 计算出的宽度和原始的宽度不相同，并且我也更新了xib创建的view怎么正确使用·DR_·设置圆角的例子和相应的api

**Comment by xingze0308** [comment]
@gitKun  谢谢回答 还想请教一个问题 我在tableview中的Cell中有一个collectionView   collectionViewCell中对UILabel切圆角 但是有一些小bug 在真机上面UILabel切成圆角了 但是UILabel 的底部确出现了一条边框线 请问能帮忙解答下吗?

**Comment by xingze0308** [comment]
UILabel的顶部或者底部有一条线 颜色是UILabel 的背景色 [捂脸][捂脸] 希望大神能指点
